.TH "XCALIB" "1" "07 July 2007" "Stefan Dohla" "xcalib"
.SH "NAME" 
xcalib \- Tiny monitor calibration loader for Xorg. 
.SH "SYNOPSIS" 
.PP 
\fBxcalib [\fB-options\fR] ICCPROFILE
.SH "DESCRIPTION" 
.PP 
\fBxcalib\fR loads 'vcgt'-tag of ICC profiles to the X-server using the
XVidMode Extension in order to calibrate your display.
.SH "OPTIONS"
.IP "\fB-d\fP, \fB-display <host:dpy>\fP" 10
.IP "\fB-s\fP, \fB-screen <screen-#>\fP" 10
.IP "\fB-c\fP, \fB-clear\fP" 10
.IP "\fB-n\fP, \fB-noaction\fP" 10
.IP "\fB-v\fP, \fB-verbose\fP" 10
.IP "\fB-p\fP, \fB-printramps\fP" 10
.IP "\fB-l\fP, \fB-loss\fP" 10
.IP "\fB-i\fP, \fB-invert\fP" 10
.IP "\fB-gc\fP, \fB-gammacor <gamma>\fP" 10
.IP "\fB-b\fP, \fB-brightness <percent>\fP" 10
.IP "\fB-co\fP, \fB-contrast <percent>\fP" 10
.IP "\fB-red <gamma> <brightness-percent> <contrast-percent>\fP" 10
.IP "\fB-green <gamma> <brightness-percent> <contrast-percent>\fP" 10
.IP "\fB-blue <gamma> <brightness-percent> <contrast-percent>\fP" 10
.IP "\fB-a\fP, \fB-alter\fP" 10
.IP "\fB-h\fP, \fB-help\fP" 10
.IP "\fB-version\fP" 10
.PP
Last parameter MUST be an ICC profile containing a vcgt or mLUT tag
or empty if the "-a" or "-alter" paramter is used or the LUT is to
be cleared.
.SH "SEE ALSO" 
.PP 
Homepage: <http://www.etg.e-technik.uni-erlangen.de/web/doe/xcalib/> 
.SH "AUTHOR" 
Stefan Dohla <stefan AT doehla DOT de>
.PP 
.SH "OTHER"
.PP
This manual page was written by Jorge Salamero Sanz <bencer@cauterized.net> for the Debian GNU/Linux system (but may be used by others). Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License version 2 or any later version published by the Free Software Foundation.
